<?php

use yii\db\Migration;

class m190805_094318_add_table_site_order extends Migration
{
    const TABLE_SITE_ORDER = '{{%site_order}}';

    public $db = 'dbStat';


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->db = Yii::$app->dbStat;
    }

    public function safeUp()
    {
        $this->createTable(self::TABLE_SITE_ORDER, [
            'id' => $this->primaryKey(),
            'order_id' => $this->integer()->notNull(),
            'order_kfss' => $this->integer(),
            'order_created_at' => $this->bigInteger()
        ]);

    }

    public function safeDown()
    {
        $this->dropTable(self::TABLE_SITE_ORDER);
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m190805_094318_add_table_site_order cannot be reverted.\n";

        return false;
    }
    */
}
