<?php

use yii\db\Migration;

class m190806_150908_add_change_column_in_site_order extends Migration
{
    const TABLE_SITE_ORDER = '{{%site_order}}';

    public $db = 'dbStat';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->db = Yii::$app->dbStat;
    }

    public function safeUp()
    {
        $this->addColumn(self::TABLE_SITE_ORDER,'order_date', $this->dateTime()->notNull());

    }

    public function safeDown()
    {
        echo "m190806_150908_add_change_column_in_site_order cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m190806_150908_add_change_column_in_site_order cannot be reverted.\n";

        return false;
    }
    */
}
