<?php

namespace common\models;


use common\helpers\ArrayHelper;
use common\models\query\CmsContentElementQuery;

class Brand extends CmsContentElement
{
    const CONTENT_ID = 193;

    //Кол-во элементов в главном меню
    const MAIN_MENU_LIMIT = 10;

    //Кол-во элементов в блоке топ брендов в расчете на каждую категорию
    const TOP_BLOCK_LIMIT_PER_CATEGORY = 4;

    const SLIDER_LIMIT = 20;

    const LITERAL_MODE = 'abc';

    const CATALOG_MODE = 'catalog';

    const COUNT_DEFAULT = 0;

    public static $literalCategories = [
        "latin" => "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
        "cyrillic" => "А - Я",
        "digit" => "1 2 3"
    ];

    public static $brandsCountCatalog = 18;
    public static $popularByTree = []; //Фиговый вариант, сделан в качестве быстрого вариака для АПИ с разделами и доп меню в них ( modules/api/resource/Category.php )


    public $cardsCount = 0;
    public $cardsCountCanSale = 0;

    private static $brandsList = [
        [
            'id' => 1,
            'active' => 1,
            'type' => 1,
            'name' => 'akvamarin',
            'description' => '',
            'image_sm' => 'img/brands/akvamarin.jpg',
            'url' => '',
        ],
        [
            'id' => 2,
            'active' => 1,
            'type' => 2,
            'name' => 'Alcatel',
            'description' => '',
            'image_sm' => 'img/brands/Alcatel.jpg',
            'url' => '/promo/page/alcatel/',
        ],
        [
            'id' => 3,
            'active' => 1,
            'type' => 2,
            'name' => 'Alpina',
            'description' => '',
            'image_sm' => 'img/brands/Alpina.jpg',
            'url' => '',
        ],
        [
            'id' => 4,
            'active' => 1,
            'type' => 2,
            'name' => 'amarti.jpg',
            'description' => '',
            'image_sm' => 'img/brands/amarti.jpg',
            'url' => '',
        ],
        [
            'id' => 5,
            'active' => 1,
            'type' => 2,
            'name' => 'Analpa.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Analpa.jpg',
            'url' => '',
        ],
        [
            'id' => 6,
            'active' => 1,
            'type' => 2,
            'name' => 'Archos.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Archos.jpg',
            'url' => '/promo/page/archos/',
        ],
        [
            'id' => 7,
            'active' => 1,
            'type' => 2,
            'name' => 'art-dtex.jpg',
            'description' => '',
            'image_sm' => 'img/brands/art-dtex.jpg',
            'url' => '',
        ],
        [
            'id' => 8,
            'active' => 1,
            'type' => 2,
            'name' => 'Artesa.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Artesa.jpg',
            'url' => '',
        ],
        [
            'id' => 9,
            'active' => 1,
            'type' => 2,
            'name' => 'Asus.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Asus.jpg',
            'url' => '',
        ],
        [
            'id' => 10,
            'active' => 1,
            'type' => 2,
            'name' => 'baltzoloto.jpg',
            'description' => '',
            'image_sm' => 'img/brands/baltzoloto.jpg',
            'url' => '',
        ],
        [
            'id' => 11,
            'active' => 1,
            'type' => 2,
            'name' => 'Blagoff.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Blagoff.jpg',
            'url' => '/promo/page/blagof/',
        ],
        [
            'id' => 12,
            'active' => 1,
            'name' => 'Borner.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Borner.jpg',
            'url' => '',
        ],
        [
            'id' => 13,
            'active' => 1,
            'type' => 2,
            'category' => [], //Электроника
            'name' => 'BQ.jpg',
            'description' => '',
            'image_sm' => 'img/brands/BQ.jpg',
            'url' => '/promo/page/bq/',
        ],
        [
            'id' => 14,
            'active' => 1,
            'type' => 2,
            'name' => 'braun.jpg',
            'description' => '',
            'image_sm' => 'img/brands/braun.jpg',
            'url' => '/promo/page/braun/',
        ],
        [
            'id' => 15,
            'active' => 1,
            'name' => 'Brillare.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Brillare.jpg',
            'url' => '',
        ],
        [
            'id' => 16,
            'active' => 1,
            'type' => 2,
            'name' => 'bronnisk.jpg',
            'description' => '',
            'image_sm' => 'img/brands/bronnisk.jpg',
            'url' => '',
        ],
        [
            'id' => 17,
            'active' => 1,
            'type' => 2,
            'name' => 'Calipso.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Calipso.jpg',
            'url' => '',
        ],
        [
            'id' => 18,
            'active' => 1,
            'type' => 2,
            'name' => 'Clarks.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Clarks.jpg',
            'url' => '',
        ],
        [
            'id' => 19,
            'active' => 1,
            'type' => 2,
            'name' => 'Daewoo.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Daewoo.jpg',
            'url' => '',
        ],
        [
            'id' => 20,
            'active' => 1,
            'type' => 2,
            'category' => [], //Электроника
            'name' => 'DIGMA.jpg',
            'description' => '',
            'image_sm' => 'img/brands/DIGMA.jpg',
            'url' => '/promo/page/digma/',
        ],
        [
            'id' => 21,
            'active' => 1,
            'type' => 2,
            'category' => [], //Электроника
            'name' => 'Doogee.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Doogee.jpg',
            'url' => '/promo/page/doogee/',
        ],
        [
            'id' => 22,
            'active' => 1,
            'type' => 2,
            'name' => 'efremov.jpg',
            'description' => '',
            'image_sm' => 'img/brands/efremov.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Fly.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Fly.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'gutmorgen.jpg',
            'description' => '',
            'image_sm' => 'img/brands/gutmorgen.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Haier.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Haier.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Honor.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Honor.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Huawei.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Huawei.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'IN_STEP.jpg',
            'description' => '',
            'image_sm' => 'img/brands/IN_STEP.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'category' => [], //
            'name' => 'Inoi.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Inoi.jpg',
            'url' => '/promo/page/inoi/',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'IPKEN.jpg',
            'description' => '',
            'image_sm' => 'img/brands/IPKEN.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Irbis.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Irbis.jpg',
            'url' => '/promo/page/irbis/',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'kitfort.jpg',
            'description' => '',
            'image_sm' => 'img/brands/kitfort.jpg',
            'url' => '/promo/page/kitfort/',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Koronateks.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Koronateks.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Krups.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Krups.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'LAVIRA.jpg',
            'description' => '',
            'image_sm' => 'img/brands/LAVIRA.jpg',
            'url' => '/promo/page/lavira/',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Loricci.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Loricci.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Luminarc.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Luminarc.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Marco_Tozzi.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Marco_Tozzi.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Matilda-tm.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Matilda-tm.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Meizu.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Meizu.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Midea.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Midea.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'midisa.jpg',
            'description' => '',
            'image_sm' => 'img/brands/midisa.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'category' => [], //
            'name' => 'Motorola.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Motorola.jpg',
            'url' => '/promo/page/motorola/',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Moulinex.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Moulinex.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'negateks.jpg',
            'description' => '',
            'image_sm' => 'img/brands/negateks.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Nobby.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Nobby.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Nokia.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Nokia.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'OLMIS.jpg',
            'description' => '',
            'image_sm' => 'img/brands/OLMIS.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'OLSI.jpg',
            'description' => '',
            'image_sm' => 'img/brands/OLSI.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Ortomoda.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Ortomoda.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Otiko.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Otiko.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'PALLA.jpg',
            'description' => '',
            'image_sm' => 'img/brands/PALLA.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Philips.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Philips.jpg',
            'url' => '/promo/page/philips/',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'PRESTIGE_STYLE.jpg',
            'description' => '',
            'image_sm' => 'img/brands/PRESTIGE_STYLE.jpg',
            'url' => '/promo/page/prestige-style/',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Prestigio.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Prestigio.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'category' => [], //
            'name' => 'Pretty_Woman.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Pretty_Woman.jpg',
            'url' => '/promo/page/pretty-woman/',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'category' => [], //
            'name' => 'Redmond.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Redmond.jpg',
            'url' => '/promo/page/redmond/',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Respect.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Respect.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Rondell.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Rondell.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Ronnon.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Ronnon.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'roswest.jpg',
            'description' => '',
            'image_sm' => 'img/brands/roswest.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Russell_Hobbs.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Russell_Hobbs.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Salamander.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Salamander.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Samsung.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Samsung.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Scarlett.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Scarlett.jpg',
            'url' => '/promo/page/scarlett/',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Selteks.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Selteks.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'shoiberg.jpg',
            'description' => '',
            'image_sm' => 'img/brands/shoiberg.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Sinbo.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Sinbo.jpg',
            'url' => '/promo/page/sinbo/',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'sokolov.jpg',
            'description' => '',
            'image_sm' => 'img/brands/sokolov.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Sony.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Sony.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'SPARADA.jpg',
            'description' => '',
            'image_sm' => 'img/brands/SPARADA.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'SPUR.jpg',
            'description' => '',
            'image_sm' => 'img/brands/SPUR.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'tamaris.jpg',
            'description' => '',
            'image_sm' => 'img/brands/tamaris.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Tecno.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Tecno.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Tefal.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Tefal.jpg',
            'url' => '/promo/page/tefal/',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'TEOSA.jpg',
            'description' => '',
            'image_sm' => 'img/brands/TEOSA.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Tervolina.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Tervolina.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'TexDesign.jpg',
            'description' => '',
            'image_sm' => 'img/brands/TexDesign.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'category' => [], //
            'name' => 'teXet.jpg',
            'description' => '',
            'image_sm' => 'img/brands/teXet.jpg',
            'url' => '/promo/page/texet/',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Textile_House.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Textile_House.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Tofa.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Tofa.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Tomilochka_Moda_TM.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Tomilochka_Moda_TM.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'vacilisa.jpg',
            'description' => '',
            'image_sm' => 'img/brands/vacilisa.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'VERTEX.jpg',
            'description' => '',
            'image_sm' => 'img/brands/VERTEX.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Vitacci.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Vitacci.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Vitek.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Vitek.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Vitesse.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Vitesse.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Xiaomi.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Xiaomi.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Yukostyle.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Yukostyle.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Yunichel.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Yunichel.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'Zenden.jpg',
            'description' => '',
            'image_sm' => 'img/brands/Zenden.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'ZTE.jpg',
            'description' => '',
            'image_sm' => 'img/brands/ZTE.jpg',
            'url' => '',
        ],
        [
            'id' => 1,
            'active' => 1,
            'type' => 2,
            'name' => 'BLACK&DECKER.jpg',
            'description' => '',
            'image_sm' => 'img/brands/BLACK&DECKER.jpg',
            'url' => '',
        ],
    ];


    private static $brandsImagesList = [
//        'adameva' => 'Adam&Eva' 8438223,
//        'almi-comfort' => 'almi-comfort' 6498985,
//        'bali-art' => 'bali-art',
//        'berlingerhaus' => 'berlingerhaus',
//        'black-decker' => 'black-decker',
//        'bridget' => 'bridget',
//        'der-spur' => 'der-spur',
//        'dorothys-home' => 'dorothys-home',
//        'dosh-home' => 'dosh-home',
//        'dreambag' => 'dreambag',
//        'emsa' => 'emsa',
//        'exe' => 'exe',
//        'farmstay' => 'farmstay',
//        'fk' => 'fk',
//        'freya-collection' => 'freya-collection',
//        'hortus-fratris' => 'hortus-fratris',
//        'jarko' => 'jarko',
//        'merlis' => 'merlis',
//        'notte-bianca' => 'notte-bianca',
//        'plist' => 'plist',
//        'polaris' => 'polaris',
//        'pre-woman' => 'pre-woman',
//        'pro-shield' => 'pro-shield',
//        'remiling-household' => 'remiling-household',
//        'skarlett' => 'skarlett',
//        'sokolov-jewerly' => 'sokolov-jewerly',
//        'starwind' => 'starwind',
//        'stile-di-vita' => 'stile-di-vita',
//        'sunlight' => 'sunlight',
//        'viko' => 'viko',
//        'werner' => 'werner',
//        'zeidan' => 'zeidan',
//        'zinger' => 'zinger',
//        'zks' => 'zks',
//        'АДАМАНТ' => 'adamant',
//        'Алримекс' => 'alrimeks',
//        'Анастасия Мак' => 'anastasia-mak',
//        'Артесса' => 'artessa',
//        'БАЛТИЙСКОЕ ЗОЛОТО' => 'baltijskoe-zoloto',
//        'Бронницкий ювелир' => 'bronnickij-uvelir',
//        'Василиса' => 'vasilisa',
//        'Дарвин' => 'darvin',
//        'Дарисса Фэшн' => 'darissa-fesn',
//        'ДЕ ЛЮКС' => 'de-luks',
//        'dzunaid' => 'Джунаид',
//        'krymskaa-kosmetika' => 'КРЫМСКАЯ КОСМЕТИКА',
//        'lori-najt' => 'Лори-Найт',
//        'mateks' => 'Матекс',
//        'matrena' => 'Матрена',
//        'miss-lora' => 'Мисс Лора',
//        'nacionalnoe-dostoanie' => 'национальное достояние',
//        'polina' => 'Полина',
//        'serebranyj-dozd' => 'Серебряный дождь',
//        'siren' => 'Сирень',
//        'teks-dizajn' => 'Текс-Дизайн',
//        'hepiness' => 'Хепинесс',
//        'elegant-stajl' => 'Элегант стайл',
//        'ulia-sehodanova' => 'Юлия Шеходанова',

        '8336622' => 'img/brands/agness.jpg',
        '8440612' => 'img/brands/1001dress.jpg',
        '1026545' => 'img/brands/amadeus.jpg',
        '1026744' => 'img/brands/amazone.jpg',
        '12899975' => 'img/brands/ametrin.jpg',
        '8701742' => 'img/brands/anskin.jpg',
        '1026424' => 'img/brands/ark.jpg',
        '8433784' => 'img/brands/ascot.jpg',
        '8482292' => 'img/brands/barmariska.jpg',
        '1667222' => 'img/brands/bayerhoff.jpg',
        '8701806' => 'img/brands/bayerhoff.jpg',
        '1026292' => 'img/brands/berrisom.jpg',
        '8490913' => 'img/brands/beurer.jpg',
        '1635477' => 'img/brands/bio-textiles.jpg',
        '8701778' => 'img/brands/bio-textiles.jpg',
        '8489541' => 'img/brands/charlette.jpg',
        '1026579' => 'img/brands/charmante.jpg',
        '8701746' => 'img/brands/daeng-gi-meo-ri.jpg',
        '1026427' => 'img/brands/de-fleur.jpg',
        '8701707' => 'img/brands/deify.jpg',
        '1026557' => 'img/brands/delta.jpg',
        '8701709' => 'img/brands/dianida.jpg',
        '8478022' => 'img/brands/disorelle.jpg',
        '1026537' => 'img/brands/dolce-vita.jpg',
        '8701749' => 'img/brands/dr-sea.jpg',
        '1026558' => 'img/brands/ecos.jpg',
        '1026389' => 'img/brands/farmstay.jpg',
        '8701716' => 'img/brands/forus.jpg',
        '8701813' => 'img/brands/frank-moller.jpg',
        '8379133' => 'img/brands/glasslock.jpg',
        '8701758' => 'img/brands/global-white.jpg',
        '8221390' => 'img/brands/goodzone.jpg',
        '1026667' => 'img/brands/gorenje.jpg',
        '1778723' => 'img/brands/graciana.jpg',
        '1026592' => 'img/brands/harper.jpg',
        '1026366' => 'img/brands/homestar.jpg',
        '1026512' => 'img/brands/hoover.jpg',
        '1026383' => 'img/brands/hortus_fratris.jpg',
        '1026462' => 'img/brands/hyundai.jpg',
        '8215459' => 'img/brands/inblu.jpg',
        '8223254' => 'img/brands/indiana.jpg',
        '1026318' => 'img/brands/irit.jpg',
        '1026473' => 'img/brands/jana.jpg',
        '1026617' => 'img/brands/jarko.jpg',
        '8701787' => 'img/brands/kamille.jpg',
        '8701691' => 'img/brands/kristina.jpg',
        '8221391' => 'img/brands/kumfo.jpg',
        '8429728' => 'img/brands/la-via-estelar.jpg',
        '1026564' => 'img/brands/limonti.jpg',
        '1770961' => 'img/brands/lina.jpg',
        '8315096' => 'img/brands/louis-gourmet.jpg',
        '1026468' => 'img/brands/Mallony.jpg',
        '1026662' => 'img/brands/maxvi.jpg',
        '1026597' => 'img/brands/mayerboch.jpg',
        '1324515' => 'img/brands/mercury.jpg',
        '1026430' => 'img/brands/micromax.jpg',
        '8465944' => 'img/brands/milana-style.jpg',
        '1026692' => 'img/brands/millerhaus.jpg',
        '8701705' => 'img/brands/modress.jpg',
        '8476252' => 'img/brands/montserrat.jpg',
        '8701825' => 'img/brands/murano-art.jpg',
        '8526596' => 'img/brands/mw-light.jpg',
        '8701829' => 'img/brands/nellex.jpg',
        '8492568' => 'img/brands/oemen.jpg',
        '8701763' => 'img/brands/pani-walewska.jpg',
        '1026781' => 'img/brands/park.jpg',
        '8684132' => 'img/brands/paters.jpg',
        '8277350' => 'img/brands/rekam.jpg',
        '1026697' => 'img/brands/ritmix.jpg',
        '8477124' => 'img/brands/rocket-soap.jpg',
        '1026770' => 'img/brands/rosenberg.jpg',
        '1026742' => 'img/brands/salvi.jpg',
        '8255384' => 'img/brands/scholl.jpg',
        '1026649' => 'img/brands/silicon-power.jpg',
        '8701800' => 'img/brands/skin-factory.jpg',
        '8701766' => 'img/brands/sosu.jpg',
        '8701711' => 'img/brands/staix.jpg',
        '8322870' => 'img/brands/stinger.jpg',
        '1026611' => 'img/brands/strobs.jpg',
        '8417005' => 'img/brands/take-it.jpg',
        '8701789' => 'img/brands/td-valeriya.jpg',
        '1026457' => 'img/brands/tesla.jpg',
        '8701739' => 'img/brands/thermos.jpg',
        '12885643' => 'img/brands/vesna-jewelry.jpg',
        '8449428' => 'img/brands/visavis.jpg',
        '8322871' => 'img/brands/wenger.jpg',
        '1026551' => 'img/brands/x-lady.jpg',
        '1026761' => 'img/brands/zillinger.jpg',
        '8701680' => 'img/brands/alkor.jpg',
        '1026663' => 'img/brands/gercina.jpg',
        '1026701' => 'img/brands/dadzet.jpg',
        '8701688' => 'img/brands/zarina.jpg',
        '1026535' => 'img/brands/zarina.jpg',
        '8701782' => 'img/brands/Dawn_of_fashion.jpg',
        '1742605' => 'img/brands/Dawn_of_fashion.jpg',
        '1026378' => 'img/brands/GOLD_PATTERNS.jpg',
        '8605459' => 'img/brands/Royal_temptation.jpg',
        '1026572' => 'img/brands/Milada.jpg',
        '8605379' => 'img/brands/Pavlina.jpg',
        '8560083' => 'img/brands/Paris_Commune.jpg',
        '1026419' => 'img/brands/PRIMA_EXCLUSIVE.jpg',
        '1942533' => 'img/brands/RASSCVETAI.jpg',
        '8335407' => 'img/brands/Rossinka.jpg',
        '8214395' => 'img/brands/Silver_of_Russia.jpg',

        //todo непонятная ситуация, у бренда другое название и лого
//        '8214395' => 'img/brands/silver_kostroma.jpg',
        '13271793' => 'img/brands/silver_kostroma.jpg',

        '1026574' => 'img/brands/Sinel.jpg',
        '8529006' => 'img/brands/TamiTeks.jpg',

        //todo неправильный лого попросили скрыть
//        '8701720' => 'img/brands/Textile_Housee.jpg',
//        '1606679' => 'img/brands/Textile_Housee.jpg',

//        '8701702' => 'img/brands/Томилочка.jpg',
        '8223205' => 'img/brands/Trikotazhnica.jpg',
        '8425196' => 'img/brands/SHARLIS.jpg',
        '1026375' => 'img/brands/Estet.jpg',
        '1026414' => 'img/brands/Jewelry_traditions.jpg',
//        '8605458' => 'img/brands/TeksDesign.jpg',
        '13206764' => 'img/brands/bestway.jpg',
        '8378084' => 'img/brands/Cotton-and-silk.jpg',
        '12777142' => 'img/brands/finn-flare.jpg',
        '1026541' => 'img/brands/Greenworks.jpg',
        '8701775' => 'img/brands/pitgakoff.jpg',
        '12858668' => 'img/brands/wool-story.jpg',
        '8605412' => 'img/brands/artpostel.jpg',
        '1778721' => 'img/brands/almi.jpg',
        '1919498' => 'img/brands/ankoli.jpg',
        '8701689' => 'img/brands/Darissa-Fashion.jpg',
        '8329470' => 'img/brands/dosh-home.jpg',
        '8701713' => 'img/brands/Dream-World.jpg',
        '1606672' => 'img/brands/Dream-World.jpg',
//        '1026536' => 'img/brands/elena-collection.jpg',
        '1026536' => 'img/brands/elena-collection-1.jpg',
        '1026526' => 'img/brands/emansipe.jpg',
        '8701687' => 'img/brands/emansipe.jpg',
        '1606646' => 'img/brands/emansipe.jpg',
        '1026332' => 'img/brands/krez.jpg',
        '8701693' => 'img/brands/lala-style.jpg',
        '1859984' => 'img/brands/milanika.jpg',
        '8242754' => 'img/brands/sally-hansen.jpg',
        '8701796' => 'img/brands/smart-textile.jpg',
        '1026539' => 'img/brands/valza.jpg',
        '1606649' => 'img/brands/veronika-styl.jpg',
        '1026521' => 'img/brands/veronika-styl.jpg',
        '8701690' => 'img/brands/veronika-styl.jpg',
        '1026354' => 'img/brands/krasnoselskij-uvelirprom.jpg',
        '13193070' => 'img/brands/zks.jpg',
        '8701770' => 'img/brands/crimean_cosmetics.jpg',
        '1632212' => 'img/brands/crimean_cosmetics.jpg',
        '8688478' => 'img/brands/lunnyj-svet.jpg',
        '1026400' => 'img/brands/milanikaa.jpg',
        '1026669' => 'img/brands/start.jpg',
        '8701741' => 'img/brands/adelline.jpg',
        '8701697' => 'img/brands/alina.jpg',
        '12858666' => 'img/brands/allmodi.jpg',
        '12917184' => 'img/brands/apsara.jpg',
        '8470149' => 'img/brands/arnica.jpg',
        '8263204' => 'img/brands/astrum.jpg',
        '1006161' => 'img/brands/atlanta.jpg',
        '1026301' => 'img/brands/atlanta.jpg',
        '8690937' => 'img/brands/atlasformen.jpg',
        '1006611' => 'img/brands/aurora.jpg',
        '1026507' => 'img/brands/aurora.jpg',
        '8701785' => 'img/brands/ayoume.jpg',
        '1006390' => 'img/brands/balex.jpg',
        '1026696' => 'img/brands/balex.jpg',
        '1006339' => 'img/brands/bekker.jpg',
        '1026635' => 'img/brands/bekker.jpg',
        '8701685' => 'img/brands/beluchi.jpg',
        '8625258' => 'img/brands/berghoff.jpg',
        '1026586' => 'img/brands/bergner.jpg',
        '8325910' => 'img/brands/binitra-bini.jpg',
        '8701682' => 'img/brands/bissell.jpg',
        '1026275' => 'img/brands/bosch.jpg',
        '1026590' => 'img/brands/bradex.jpg',
        '8466725' => 'img/brands/burlesco.jpg',
        '8701816' => 'img/brands/cheongkwanjang.jpg',
        '8501474' => 'img/brands/crystal-bohemia.jpg',
        '8701812' => 'img/brands/diamonele.jpg',
        '8450928' => 'img/brands/doctorcos.jpg',
        '8701750' => 'img/brands/drgo.jpg',
        '8417006' => 'img/brands/ecotex.jpg',
        '12805853' => 'img/brands/edelson.jpg',
        '8601153' => 'img/brands/efor.jpg',
        '8438222' => 'img/brands/elenatex.jpg',
        '1026559' => 'img/brands/energy.jpg',
        '12874934' => 'img/brands/gemlux.jpg',
        '8701756' => 'img/brands/gess.jpg',
        '8701757' => 'img/brands/gezatone.jpg',
        '11059217' => 'img/brands/gipfel.jpg',
        '8701719' => 'img/brands/Greenlight.jpg',
        '8331963' => 'img/brands/hottek.jpg',
        '1026654' => 'img/brands/htc.jpg',
        '8529341' => 'img/brands/iris.jpg',
        '1026529' => 'img/brands/janome.jpg',
        '8430469' => 'img/brands/jw.jpg',
        '1057806' => 'img/brands/karcher.jpg',
        '8710622' => 'img/brands/kauffort.jpg',
        '1026538' => 'img/brands/kontaly.jpg',
        '8701700' => 'img/brands/ledy-di.jpg',
        '1026441' => 'img/brands/lefard.jpg',
        '1026373' => 'img/brands/lenovo.jpg',
        '8701760' => 'img/brands/lirene.jpg',
        '8230600' => 'img/brands/loraine.jpg',
        '8577805' => 'img/brands/maabada.jpg',
        '1778722' => 'img/brands/marko.jpg',
        '1026575' => 'img/brands/Matex.jpg',
        '8464706' => 'img/brands/maxclinic.jpg',
        '12899702' => 'img/brands/megapolis.jpg',
        '8704566' => 'img/brands/oursson.jpg',
        '12858669' => 'img/brands/polina-klein.jpg',
        '1026362' => 'img/brands/pomi-doro.jpg',
        '1026334' => 'img/brands/primanova.jpg',
        '8701734' => 'img/brands/primavera.jpg',
        '8701826' => 'img/brands/redox.jpg',
        '8364909' => 'img/brands/santegra.jpg',
        '8610706' => 'img/brands/savage.jpg',
        '8597369' => 'img/brands/scanndi.jpg',
        '8695970' => 'img/brands/selena.jpg',
        '13021671' => 'img/brands/serdolika.jpg',
        '8701765' => 'img/brands/skinlite.jpg',
        '1026315' => 'img/brands/smile.jpg',
        '8255137' => 'img/brands/stolyarov.jpg',
        '1026510' => 'img/brands/verloni.jpg',
        '8349623' => 'img/brands/vivaton.jpg',
        '1026567' => 'img/brands/wellberg.jpg',
        '8701769' => 'img/brands/wilds.jpg',
        '1026600' => 'img/brands/wilmar.jpg',
        '1026562' => 'img/brands/wisell.jpg',
        '1026460' => 'img/brands/almaz-holding.jpg',
        '8578296' => 'img/brands/visterra.jpg',
        '12860884' => 'img/brands/volsebnaa-noc.jpg',
        '1026599' => 'img/brands/zarya.jpg',
        '1026377' => 'img/brands/krasnaa-presna.jpg',
        '13206765' => 'img/brands/matrena.jpg',
        '8479673' => 'img/brands/natali.jpg',
        '8605375' => 'img/brands/odevajte.jpg',
        '1338298' => 'img/brands/ryzij-kot.jpg',
        '8701738' => 'img/brands/serebranyj-dom.jpg',
        '8701781' => 'img/brands/sibirskaa-kletcatka.jpg',
        '1606674' => 'img/brands/sks.jpg',
        '8701715' => 'img/brands/sks.jpg',
        '13193969' => 'img/brands/trikotel.jpg',
        '1026423' => 'img/brands/antarnaa-volna.jpg',



        '1026365' => 'img/brands/akvamarin.jpg',
        '13008129' => 'img/brands/Alcatel.jpg',
        'Alpina' => 'img/brands/Alpina.jpg',
        '1026566' => 'img/brands/amarti.jpg',
        'Analpa' => 'img/brands/Analpa.jpg',
        '1026345' => 'img/brands/Archos.jpg',
        'art-dtex' => 'img/brands/art-dtex.jpg',
        'Artesa' => 'img/brands/Artesa.jpg',
        '1026361' => 'img/brands/Asus.jpg',
        'baltzoloto' => 'img/brands/baltzoloto.jpg',
        '8701737' => 'img/brands/Blagoff.jpg',
        '1026682' => 'img/brands/Borner.jpg',
        '1026777' => 'img/brands/BQ.jpg',
        '8481339' => 'img/brands/braun.jpg',
        '8701704' => 'img/brands/Brillare.jpg',
        'bronnisk' => 'img/brands/bronnisk.jpg',
        'Calipso' => 'img/brands/Calipso.jpg',
        'Clarks' => 'img/brands/Clarks.jpg',
        'Daewoo' => 'img/brands/Daewoo.jpg',
        '1026643' => 'img/brands/DIGMA.jpg',
        '1026376' => 'img/brands/Doogee.jpg',
        '13008132' => 'img/brands/efremov.jpg',
        '1026589' => 'img/brands/Fly.jpg',
        'gutmorgen' => 'img/brands/gutmorgen.jpg',
        '1026401' => 'img/brands/Haier.jpg',
        'Honor' => 'img/brands/Honor.jpg',
        '1026645' => 'img/brands/Huawei.jpg',
        'IN_STEP' => 'img/brands/IN_STEP.jpg',
        '1330361' => 'img/brands/Inoi.jpg',
        '1026276' => 'img/brands/IPKEN.jpg',
        '1026364' => 'img/brands/Irbis.jpg',
        '1026298' => 'img/brands/kitfort.jpg',
        '13008120' => 'img/brands/Koronateks.jpg',
        'Krups' => 'img/brands/Krups.jpg',
        '1026585' => 'img/brands/LAVIRA.jpg',
        'Loricci' => 'img/brands/Loricci.jpg',
        '1026341' => 'img/brands/Luminarc.jpg',
        'Marco_Tozzi' => 'img/brands/Marco_Tozzi.jpg',
        'Matilda-tm' => 'img/brands/Matilda-tm.jpg',
        'Meizu' => 'img/brands/Meizu.jpg',
        'Midea' => 'img/brands/Midea.jpg',
        'midisa' => 'img/brands/midisa.jpg',
        '13008131' => 'img/brands/Motorola.jpg',
        '1026569' => 'img/brands/Moulinex.jpg',
        'negateks' => 'img/brands/negateks.jpg',
        'Nobby' => 'img/brands/Nobby.jpg',
        '13008130' => 'img/brands/Nokia.jpg',
        '13008121' => 'img/brands/OLMIS.jpg',
        '1026743' => 'img/brands/OLSI.jpg',
        'Ortomoda' => 'img/brands/Ortomoda.jpg',
        '13008124' => 'img/brands/Otiko.jpg',
        '1026632' => 'img/brands/PALLA.jpg',
        '1026343' => 'img/brands/Philips.jpg',
        '8701736' => 'img/brands/PRESTIGE_STYLE.jpg',
        '1026440' => 'img/brands/Prestigio.jpg',
        '8701714' => 'img/brands/Pretty_Woman.jpg',
        '1026561' => 'img/brands/Redmond.jpg',
        'Respect' => 'img/brands/Respect.jpg',
        '1026653' => 'img/brands/Rondell.jpg',
        '8579391' => 'img/brands/Ronnon.jpg',
        'roswest' => 'img/brands/roswest.jpg',
        '1026751' => 'img/brands/Russell_Hobbs.jpg',
        'Salamander' => 'img/brands/Salamander.jpg',
        '1026278' => 'img/brands/Samsung.jpg',
        '1026620' => 'img/brands/Scarlett.jpg',
        '8701810' => 'img/brands/Selteks.jpg',
        '13008125' => 'img/brands/shoiberg.jpg',
        '1026627' => 'img/brands/Sinbo.jpg',
        '1026673' => 'img/brands/sokolov.jpg',
        '1026647' => 'img/brands/Sony.jpg',
        '1026544' => 'img/brands/SPARADA.jpg',
        'SPUR' => 'img/brands/SPUR.jpg',
        '1026487' => 'img/brands/tamaris.jpg',
        'Tecno' => 'img/brands/Tecno.jpg',
        '1026571' => 'img/brands/Tefal.jpg',
        '1026296' => 'img/brands/TEOSA.jpg',
        '12871248' => 'img/brands/Tervolina.jpg',
        '8605458' => 'img/brands/TexDesign.jpg',
        '1026472' => 'img/brands/teXet.jpg',
        'Textile_House' => 'img/brands/Textile_House.jpg',
        'Tofa' => 'img/brands/Tofa.jpg',
        '8701702' => 'img/brands/Tomilochka_Moda_TM.jpg',
        '1606662'=> 'img/brands/Tomilochka_Moda_TM.jpg',
        '1026348' => 'img/brands/vacilisa.jpg',
        '1026658' => 'img/brands/VERTEX.jpg',
        'Vitacci' => 'img/brands/Vitacci.jpg',
        '1026359' => 'img/brands/Vitek.jpg',
        '1026576' => 'img/brands/Vitesse.jpg',
        '1026368' => 'img/brands/Xiaomi.jpg',
        '8701701' => 'img/brands/Yukostyle.jpg',
        'Yunichel' => 'img/brands/Yunichel.jpg',
        '13008128' => 'img/brands/Zenden.jpg',
        '1026394' => 'img/brands/ZTE.jpg',
        '1026552' => 'img/brands/BLACK&DECKER.jpg',
    ];

    /**
     * @inheritdoc
     * @return CmsContentElementQuery
     */
    public static function find()
    {
        return new CmsContentElementQuery(get_called_class(), ['contentId' => self::CONTENT_ID, 'tableName' => self::tableName()]);
    }

    /**
     *  Получает заголовок для сео
     */
    public function getSeoTitle()
    {
        return $this->getSeoValue('title') . ' – купить в Shop&Show';
    }

    //[DEPRECATED] Использовалась пока не было нормальных брендов из БД
    public static function getBrands($params = [])
    {
        $brands = self::$brandsList;

        $brands = array_filter($brands, function ($brand) {
            return !empty($brand['image_sm']) && !empty($brand['url']);
        });

        if (!empty($params['sort_by']) && $params['sort_by'] == 'rand') {
            shuffle($brands);
        }

        return empty($params['limit']) ? $brands : array_slice($brands, 0, $params['limit']);
    }

    public function getUrl()
    {
        return '/brands/' . $this->code . '/';
    }

    //Популярные бренды по разделам или только дял указанного раздела
    public static function getPopularByTree($params = [])
    {
        $treeId = $params['tree_id'] ?? false;
        $limit = $params['limit'] ?? false;
        $countProducts = (bool)($params['count_products'] ?? false);
        $countProductsCanSale = (bool)($params['count_products_can_sale'] ?? false);
        $onlyCanSale = (bool)($params['only_can_sale'] ?? false);

        //Если надо вернуть только с товарами доступными для продажи - обязательно считаем
        if ($onlyCanSale) {
            $countProductsCanSale = true;
        }

        $result = [];

        $brandsByPopularityByTreeQuery = BrandPopularityByTree::find()->orderBy(['popularity' => SORT_DESC]);

        if ($treeId) {
            $brandsByPopularityByTreeQuery->andWhere(['tree_id' => $treeId]);
        }

        $brandsByPopularityByTree = $brandsByPopularityByTreeQuery->all();

        if ($brandsByPopularityByTree) {
            $brandsIds = ArrayHelper::getColumn($brandsByPopularityByTree, 'brand_id');
            $brands = $brandsIds ? self::find()->andWhere(['id' => $brandsIds])->distinct()->indexBy('id')->all() : [];

//            $countProductsByBrand = [];
            if ($countProducts || $countProductsCanSale) {
                $countProductsByBrand = Product::getCardsCountByBrand($countProductsCanSale);
            }

            /** @var BrandPopularityByTree $brandTreeData */
            foreach ($brandsByPopularityByTree as $brandTreeData) {
                if ($treeId && $brandTreeData->tree_id != $treeId) {
                    continue;
                }

                if (isset($brands[$brandTreeData->brand_id])) {
                    /** @var self $brand */
                    $brand = $brands[$brandTreeData->brand_id];

                    if ($countProductsCanSale && !empty($countProductsByBrand[$brandTreeData->brand_id])) {
                        $brand->cardsCountCanSale = $countProductsByBrand[$brandTreeData->brand_id];
                    }

                    if ($countProducts && !$countProductsCanSale && !empty($countProductsByBrand[$brandTreeData->brand_id])) {
                        $brand->cardsCount = $countProductsByBrand[$brandTreeData->brand_id];
                    }

                    if (!$onlyCanSale || ($onlyCanSale && $brand->cardsCountCanSale)) {
                        $result[$brandTreeData->tree_id][] = $brand;
                    }
                }
            }
            if ($treeId) {
                $result = $result[$treeId] ?? [];
            }
            return $limit ? array_slice($result, 0, $limit) : $result;
        }

        return [];
    }

    public function getImageSrc()
    {
        return self::$brandsImagesList[$this->id] ?? '';
    }
}