<?php
/**
 * Created by PhpStorm.
 * User: nikitaignatenkov
 * Date: 2019-07-31
 * Time: 12:00
 */

namespace common\models;


use common\helpers\ArrayHelper;

class CustomMenu extends \common\models\generated\models\CustomMenu
{

    const TYPE_PROMO = 1;
    const TYPE_STOCK = 2;


    public static function getTypes($value = false)
    {
        $array = [
            self::TYPE_PROMO => 'Промо',
            self::TYPE_STOCK => 'Сток',
        ];

        return $value ? $array[$value] : $array;
    }


//    public function rules()
//    {
//        return ArrayHelper::merge(parent::rules(),[
//            ['url', 'url']
//        ]); // TODO: Change the autogenerated stub
//    }
}