<?php

namespace modules\shopandshow\components\export;


use common\interfaces\Export;

/**
 * Created by PhpStorm.
 * User: ubuntu5
 * Date: 29.09.17
 * Time: 18:24
 */
class ExportShopYandexMarketFlashPriceHandler extends YandexHandler implements Export
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->setAllColors();
        $this->name = 'YandexFlashPrice';
    }


    public function getProductQuery()
    {

        return parent::getProductQuery()
            ->andWhere(['not in', 'cms_content_element.tree_id', $this->_getExcludedCategoriesIds()]);
    }

    public function getNameForCPC()
    {
        return 'yandexflashprice';
        // TODO: Implement getNameForCPC() method.
    }
}