<?php


namespace modules\shopandshow\components\export;


use common\interfaces\Export;

class ExportShopGoogleMerchantFlashPriceHandler extends GoogleHandler implements Export
{
    public $xml = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->name = 'GoogleFlashPrice';

        $this->file_path = "/export/google/feed-flashprice.xml";

    }

    public function getProductQuery()
    {
        return parent::getProductQuery()
            ->andWhere(['not in', 'cms_content_element.tree_id', $this->_getExcludedCategoriesIds()]);

    }

    public function getNameForCPC()
    {
        return 'GoogleFlashPrice';
        // TODO: Implement getNameForCPC() method.
    }
}