<?php

namespace modules\shopandshow\components\export;


use common\helpers\ArrayHelper;
use common\interfaces\Export;
use common\models\Tree;
use Exception;
use modules\shopandshow\models\shop\ShopProduct;
use skeeks\cms\components\Cms;
use skeeks\cms\exportShopYandexMarket\ExportShopYandexMarketHandler as SXExportShopYandexMarketHandler;
use skeeks\cms\helpers\FileHelper;
use skeeks\cms\models\CmsTree;
use skeeks\cms\shop\models\ShopCmsContentElement;
use yii\helpers\Console;

class ExportShopPriceRuHandler extends YandexHandler implements Export
{


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->name = 'PriceRu';
    }


    public function getProductQuery()
    {

        return parent::getProductQuery()
            ->available();
    }

    public function getNameForCPC()
    {
        return 'priceru';
        // TODO: Implement getNameForCPC() method.
    }

    public function export()
    {
        $this->result->stdout("\tSKIP\n");
        return $this->result;

        return parent::export();
    }
}