<?php

namespace modules\shopandshow\components\export;


use common\helpers\ArrayHelper;
use common\interfaces\Export;
use common\models\Tree;
use Exception;
use modules\shopandshow\models\shop\ShopProduct;
use skeeks\cms\components\Cms;
use skeeks\cms\exportShopYandexMarket\ExportShopYandexMarketHandler as SXExportShopYandexMarketHandler;
use skeeks\cms\helpers\FileHelper;
use skeeks\cms\models\CmsTree;
use skeeks\cms\shop\models\ShopCmsContentElement;
use yii\helpers\Console;

/**
 * Created by PhpStorm.
 * User: ubuntu5
 * Date: 29.09.17
 * Time: 18:24
 */
class ExportShopYandexMarketHandler extends YandexHandler implements Export
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->name = 'Yandex';
    }


    public function getProductQuery()
    {

        return parent::getProductQuery()
            ->andWhere(['not in', 'cms_content_element.tree_id', $this->_getExcludedCategoriesIds()]);
    }

    public function getNameForCPC()
    {
        return 'yandex';
        // TODO: Implement getNameForCPC() method.
    }
}