<?php


namespace modules\shopandshow\components\export;


use common\interfaces\Export;

class ExportShopYandexMarketNewHandler extends YandexHandler implements Export
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->setAllColors();
        $this->name = 'YandexMarket';
    }


    public function getProductQuery()
    {
        return parent::getProductQuery()
            ->brandNotEmptyForCard()
            ->treeIsActive()
            ->andWhere(['not in', 'cms_content_element.tree_id', $this->_getExcludedCategoriesIds()]);
    }

    public function getNameForCPC()
    {
        return 'yandexMarket';
        // TODO: Implement getNameForCPC() method.
    }
}