<?php

namespace modules\shopandshow\components\export;


use common\helpers\ArrayHelper;
use common\helpers\Url;
use common\interfaces\Export;
use common\models\NewProduct;
use common\models\Tree;
use Exception;
use modules\shopandshow\models\shop\ShopProduct;
use skeeks\cms\components\Cms;
use skeeks\cms\exportShopYandexMarket\ExportShopYandexMarketHandler as SXExportShopYandexMarketHandler;
use skeeks\cms\helpers\FileHelper;
use skeeks\cms\models\CmsTree;
use skeeks\cms\shop\models\ShopCmsContentElement;
use yii\helpers\Console;

class FlocktoryHandler extends YandexHandler implements Export
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->name = 'Flocktory Export';


        if (!$this->file_path) {
            $this->file_path = "/export/flocktory/feed.xml";
        }
    }


    public function getNameForCPC()
    {
        return 'flocktory';
        // TODO: Implement getNameForCPC() method.
    }
}