<?php
/**
 * Created by PhpStorm.
 * User: nikitaignatenkov
 * Date: 2019-08-21
 * Time: 11:10
 */

namespace modules\api\resource;

use common\helpers\Size;
use common\thumbnails\Thumbnail;


class NewProduct extends Product
{

    // todo this resource
    public function fields()
    {
        /** @var \common\models\NewProduct $this */
        return [
            'id',
            'name',
            'image',
            'url',
            'thumbnails' => function () {
                $imagesData = [];
                foreach ($this->images as $image) {
                    $imagesData[] =
                        \Yii::$app->imaging->thumbnailUrlSS($image->src,
                            new Thumbnail([
                                'w' => 608, // 220, // 218
                                'h' => 608, // 220, // 413
                            ])
                        );
                }
                return $imagesData;
            },
            'price' => function () {
                return [
                    'current' => 1,
                    'old' => 2
                ];
            },
            'discount' => function () {

            },
            'rating' => function () {
                return [
                    'value' => 1,
                    'max' => 2,
                    'step' => 2,
                ];
            },
            'badge' => function () {
                return 1;
            },
            'attributes' => function () {
                return [
                    [
                        'id' => 0,
                        'name' => 'Размер',
                        'options' => Size::getLotSizes($this->isLot() ? $this->id : $this->parent_content_element_id)
                    ]
                ];
            }

        ];
//        return
        return parent::fields(); // TODO: Change the autogenerated stub
    }

}