<?php

namespace modules\api\resource;

use common\models\cmsContent\CmsContentElement;

class Resourse extends CmsContentElement
{

    /**
     * Ид базовой цены
     * @var null
     */
    static $basePriceId = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (!self::$basePriceId) {
            $basePriceRow = \Yii::$app->db->createCommand("SELECT id FROM `shop_type_price` WHERE `code` = 'BASE'")->queryOne(); // 4

            if (!$basePriceRow) {
                throw new Exception('Нет базовой цены!');
            }

            self::$basePriceId = $basePriceRow['id'];
        }
    }

}