<?php

$queue = 'siteExchange'; // Компонент подключения к очереди прописанный в config/main
$vhost = '/';

if (!defined('QUEUE_PREFIX')) {
    $queuePrefix = 'site';
} else {
    $queuePrefix = QUEUE_PREFIX;
}
// onlySave => true, если надо быстро забрать из очереди все лоты, а потом в многопоточном режиме загрузить в базу: php yii queues/daemon/start-log
// Отключение логирования очереди 'nolog' => true,
return [
    'product' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'TovarExchange',
        'queueName' => $queuePrefix . '.Product',
        'jobClass' => '\console\controllers\queues\jobs\products\Product',
        'routingKey' => 'KFSS.OFFER_CONTENT',
        //'onlySave' => true,
    ],
    'lot' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'LotExchange',
        'queueName' => $queuePrefix . '.Lot',
        'jobClass' => '\console\controllers\queues\jobs\products\PropertiesCollection',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'product_mainprops' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'TovarExchange',
        'queueName' => $queuePrefix . '.ProductMainProps',
        'jobClass' => '\console\controllers\queues\jobs\products\MainProp',
        'routingKey' => 'KFSS.MAIN_PROP',
        //'onlySave' => true,
    ],
    'product_props' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'OffcntPropExchange',
        'queueName' => $queuePrefix . '.ProductProperty',
        'jobClass' => '\console\controllers\queues\jobs\products\Property',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'product_props_1' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'OffcntPropExchange',
        'queueName' => $queuePrefix . '.ProductProperty',
        'jobClass' => '\console\controllers\queues\jobs\products\Property',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'product_props_2' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'OffcntPropExchange',
        'queueName' => $queuePrefix . '.ProductProperty',
        'jobClass' => '\console\controllers\queues\jobs\products\Property',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'product_props_3' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'OffcntPropExchange',
        'queueName' => $queuePrefix . '.ProductProperty',
        'jobClass' => '\console\controllers\queues\jobs\products\Property',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'product_props_add' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'OffcntPropAddExchange',
        'queueName' => $queuePrefix . '.ProductPropertyAdd',
        'jobClass' => '\console\controllers\queues\jobs\products\PropertyAdd',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'product_classificator' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'OffcntClassExchange',
        'queueName' => $queuePrefix . '.ProductClassificator',
        'jobClass' => '\console\controllers\queues\jobs\products\Classificator',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'product_media' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'MediaContentExchange',
        'queueName' => $queuePrefix . '.ProductMedia',
        'jobClass' => '\console\controllers\queues\jobs\products\MediaContent',
        'routingKey' => 'KFSS.MEDIA_CONTENT2',
        //'onlySave' => true,
    ],
    'product_users' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'OffcntUsrExchange',
        'queueName' => $queuePrefix . '.ProductUsers',
        'jobClass' => '\console\controllers\queues\jobs\products\Users',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'product_price' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'OffcntPriceExchange',
        'queueName' => $queuePrefix . '.ProductPrice',
        'jobClass' => '\console\controllers\queues\jobs\products\Price',
        'routingKey' => '#',
//        'onlySave' => true,
    ],
    'product_price_2' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'OffcntPriceExchange',
        'queueName' => $queuePrefix . '.ProductPrice',
        'jobClass' => '\console\controllers\queues\jobs\products\Price',
        'routingKey' => '#',
//        'onlySave' => true,
    ],
    'product_price_3' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'OffcntPriceExchange',
        'queueName' => $queuePrefix . '.ProductPrice',
        'jobClass' => '\console\controllers\queues\jobs\products\Price',
        'routingKey' => '#',
//        'onlySave' => true,
    ],
    'product_price_4' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'OffcntPriceExchange',
        'queueName' => $queuePrefix . '.ProductPrice',
        'jobClass' => '\console\controllers\queues\jobs\products\Price',
        'routingKey' => '#',
//        'onlySave' => true,
    ],
    'product_links' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'OffcntLnkExchange',
        'queueName' => $queuePrefix . '.ProductLinks',
        'jobClass' => '\console\controllers\queues\jobs\products\Links',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    //Приходят значения кол-ва меньше 0, что странно при положительных остатках в модификациях
    //Отключим, остатки по лоту будем считать из модификаций (если их нет, то сработает базовая модификация
    //Включим что бы читалось, что бы не скапливалось пока очередь не отрубят, но будем скипать при обработке
    'reserve_lot' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'ReserveLotExchange',
        'queueName' => $queuePrefix . '.ReserveLot',
        'jobClass' => '\console\controllers\queues\jobs\shop\Reserve',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'reserve_mod' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'ReserveModExchange',
        'queueName' => $queuePrefix . '.ReserveMod',
        'jobClass' => '\console\controllers\queues\jobs\shop\Reserve',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'reserve_mod_2' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'ReserveModExchange',
        'queueName' => $queuePrefix . '.ReserveMod',
        'jobClass' => '\console\controllers\queues\jobs\shop\Reserve',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    // пока отключаем, чтобы не поехало меню. Ждем новый классификатор
    /*'classificator' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'ClassificatorNodeExchange',
        'queueName' => $queuePrefix.'.Classificator',
        'jobClass' => '\console\controllers\queues\jobs\tree\Classificator',
        'routingKey' => '#',
        //'onlySave' => true,
    ],*/
    'rubricator' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'CategoryNodeExchange',
        'queueName' => $queuePrefix.'.CategoryNode',
        'jobClass' => '\console\controllers\queues\jobs\tree\Rubricator',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'property' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'PropertyExchange',
        'queueName' => $queuePrefix . '.Property',
        'jobClass' => '\console\controllers\queues\jobs\dicts\Property',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'property_item' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'PropertyItemExchange',
        'queueName' => $queuePrefix . '.PropertyItem',
        'jobClass' => '\console\controllers\queues\jobs\dicts\PropertyItem',
        'routingKey' => '#',
        //'onlySave' => true,
    ],

    'brand' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'BrandExchange',
        'queueName' => $queuePrefix . '.Brand',
        'jobClass' => '\console\controllers\queues\jobs\dicts\Brand',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
//    'supplier' => [
//        'queue' => $queue,
//        'vhost' => $vhost,
//        'exchangeName' => 'SupplierExchange',
//        'queueName' => $queuePrefix.'.Supplier',
//        'jobClass' => '\console\controllers\queues\jobs\dicts\Supplier',
//        'routingKey' => '#',
//        //'onlySave' => true,
//    ],
    'season' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'SeasonExchange',
        'queueName' => $queuePrefix . '.Season',
        'jobClass' => '\console\controllers\queues\jobs\dicts\Season',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'size' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'SizeExchange',
        'queueName' => $queuePrefix . '.Size',
        'jobClass' => '\console\controllers\queues\jobs\dicts\MerchSize',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'color' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'ColorExchange',
        'queueName' => $queuePrefix . '.Color',
        'jobClass' => '\console\controllers\queues\jobs\dicts\Color',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'order' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'OrderMainExchange',
        'queueName' => $queuePrefix . '.Order',
        'jobClass' => '\console\controllers\queues\jobs\shop\Order',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'order_pos' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'OrderPosExchange',
        'queueName' => $queuePrefix . '.OrderPos',
        'jobClass' => '\console\controllers\queues\jobs\shop\OrderPos',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'order_status' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'OrderStatusExchange',
        'queueName' => $queuePrefix . '.OrderStatus',
        'jobClass' => '\console\controllers\queues\jobs\shop\OrderStatus',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'order_status_1' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'OrderStatusExchange',
        'queueName' => $queuePrefix . '.OrderStatus',
        'jobClass' => '\console\controllers\queues\jobs\shop\OrderStatus',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'order_status_2' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'OrderStatusExchange',
        'queueName' => $queuePrefix . '.OrderStatus',
        'jobClass' => '\console\controllers\queues\jobs\shop\OrderStatus',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'coupons' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'PromoExchange',
        'queueName' => $queuePrefix . '.PromoCoupons',
        'jobClass' => '\console\controllers\queues\jobs\shop\Coupons',
        'routingKey' => '#',
        //'onlySave' => true,
    ],
    'temp' => [
        'queue' => $queue,
        'vhost' => $vhost,
        'exchangeName' => 'TempExchange',
        'queueName' => $queuePrefix . '.Temp',
        'jobClass' => '\console\controllers\queues\jobs\dicts\Temp',
        'routingKey' => '#',
        'onlySave' => true,
    ],
];