<?php
namespace common\widgets\shares\blockslider;

use common\widgets\content\ContentElementWidget;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;

/**
 * Class BannerContentElementWidget
 * @package common\widgets\shares\blockslider
 */
class BannerContentElementWidget extends ContentElementWidget
{
    public $model;
    public $buttonText = '';
    public $buttonUrl = '';

    public function _run()
    {
//        $this->viewFile = '@frontend/themes/v3/widgets/sliders/products_6_slick';
        return parent::_run(); // TODO: Change the autogenerated stub
    }

    /**
     * Только свойства, которые будем сохранять в settings
     * @inheritdoc
     */
    public function rules() {
        return [
            [['buttonText', 'buttonUrl'], 'string'],
            ['viewFile', 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'buttonText' => 'Текст на кнопке',
            'buttonUrl' => 'Ссылка, куда перейдет пользователь по клику на кнопку'
        ]);
    }

    /**
     * @inheritdoc
     */
    public function renderConfigForm(ActiveForm $form)
    {
        echo \Yii::$app->view->renderFile(__DIR__ . '/_form.php', [
            'form'  => $form,
            'model' => $this
        ], $this);
    }
}