<?php

namespace modules\api\controllers\v2\schedule;

use common\components\cache\PageCache;
use common\helpers\ArrayHelper;
use common\helpers\CacheHelper;
use yii\rest\Controller;

class DaysController extends Controller
{
    public function behaviors()
    {
        return [
            [
                'class' => \yii\filters\ContentNegotiator::className(),
                'only' => ['index'],
                'formats' => [
                    'application/json' => \yii\web\Response::FORMAT_JSON,
                ],
            ],
            [
                'class' => PageCache::class,
                'only' => ['index'],
                'duration' => CacheHelper::CACHE_TIME_ONAIR_API,
                'variations' => CacheHelper::getOnAirApiVariation(),
                'enabled' => CacheHelper::isEnabled()
            ],
        ];
    }

    public function verbs()
    {
        $verbs = [
            'index' => ["GET"]
        ];

        return ArrayHelper::merge(parent::verbs(), $verbs); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return [
            [
                'id' => 0,
                'name' => 'Сегодня'
            ],
            [
                'id' => 1,
                'name' => 'Вчера'
            ],
            [
                'id' => 2,
                'name' => 'Позавчера'
            ],
        ];
    }
}